### ISSUE TITLE
Cosmos Mongo API Connection String Parse Error

### ISSUE THREAD

**Issue by khowling** [staticwebdev/mongoose-starter#9]
When deploying this template using the documentation, I received this error from the Functions:

```
Exception while executing function: Functions.lists Result: Failure
Exception: Error: Password contains an illegal unescaped character
Stack: Error: Password contains an illegal unescaped character
    at parseConnectionString (/home/site/wwwroot/node_modules/mongodb/lib/url_parser.js:305:13)
    at parseHandler (/home/site/wwwroot/node_modules/mongodb/lib/url_parser.js:136:14)
    at module.exports (/home/site/wwwroot/node_modules/mongodb/lib/url_parser.js:28:12)
    at deprecated (internal/util.js:89:15)
    at connect (/home/site/wwwroot/node_modules/mongodb/lib/operations/connect.js:282:3)
    at /home/site/wwwroot/node_modules/mongodb/lib/mongo_client.js:260:5
    at maybePromise (/home/site/wwwroot/node_modules/mongodb/lib/utils.js:692:3)
    at MongoClient.connect (/home/site/wwwroot/node_modules/mongodb/lib/mongo_client.js:256:10)
    at /home/site/wwwroot/node_modules/mongoose/lib/connection.js:835:12
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/home/site/wwwroot/node_modules/mongoose/lib/connection.js:832:19)
    at /home/site/wwwroot/node_modules/mongoose/lib/index.js:351:10
    at /home/site/wwwroot/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/site/wwwroot/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/home/site/wwwroot/node_modules/mongoose/lib/index.js:1149:10)
```

**Comment by GeekTrainer** [comment]
Closed by #9 with great thanks to @khowling
